[tools]
go = "latest"
java = "latest"
node = "latest"
ruby = "latest"
python = "3.13"
rust = "latest"

actionlint = "latest"
awscli = { version = "latest", symlink_bins = "true" }
deno = "latest"
duckdb = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
hugo = "latest"
jq = "latest"
kubectx = "latest"
mysql = "latest"
pandoc = "latest"
protobuf = "latest"
terraform = "latest"
yarn = "latest"
yq = "latest"

"pipx:graph-cli" = "latest"
"pipx:trafilatura" = "latest"

"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:bat" = "latest"
"cargo:sheldon" = "latest"
"cargo:git-delta" = "latest"

"github:ktr0731/evans" = "latest"
"github:k1LoW/octocov" = "latest"
