[tools]
go = "latest"
java = "latest"
node = "latest"
ruby = "latest"
python = "3.13"
rust = "latest"

actionlint = "latest"
awscli = { version = "latest", symlink_bins = "true" }
deno = "latest"
duckdb = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
hugo = "latest"
jq = "latest"
kubectx = "latest"
mysql = "latest"
pandoc = "latest"
peco = "latest"
protobuf = "latest"
terraform = "latest"
yarn = "latest"
yq = "latest"

"pipx:graph-cli" = "latest"
"pipx:trafilatura" = "latest"

"cargo:git-delta" = "latest"

"github:ktr0731/evans" = "latest"
"github:k1LoW/octocov" = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:bat" = "latest"

[tasks.github_open_repo]
description = "open github repo"
alias = "gr"
run = "gh browse"

[tasks.github_create_or_view_pr]
description = "create or view pull request with web"
alias = "gpr"
run = '''
if gh pr view &>/dev/null; then
    gh pr view -w
else
    gh pr create -w
fi
'''

[tasks.github_pr_list]
description = "browse pr list and open with web"
alias = "gprls"
run = '''
gh pr list | peco | awk '{print $1}' | xargs gh pr view --web
'''

[tasks.github_check_actions]
description = "browse status of actions"
alias = "gch"
run = "gh run list"

[tasks.kill_chrome]
description = "kill Google Chrome to reload tab status"
alias = "kc"
run = '''
kill -9 $(ps -x | grep "Google Chrome" | awk "{print $1}")
'''
