[tools]
go = "latest"
java = "latest"
node = "latest"
ruby = "latest"

actionlint = "latest"
awscli = { version = "latest", symlink_bins = "true" }
deno = "latest"
duckdb = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
hugo = "latest"
jq = "latest"
kubectx = "latest"
mysql = "latest"
pandoc = "latest"
peco = "latest"
protobuf = "latest"
terraform = "latest"
yarn = "latest"
yq = "latest"
