[tools]
go = "latest"
java = "latest"
node = "latest"
ruby = "3"
python = "latest"
rust = "latest"

actionlint = "latest"
awscli = { version = "latest", symlink_bins = "true" }
deno = "latest"
duckdb = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
jq = "latest"
kubectx = "latest"
mysql = "latest"
pandoc = "latest"
protobuf = "latest"
terraform = "latest"
yarn = "latest"
yq = "latest"
hugo = "0.152"
pipx = "latest"
gcloud = "latest"

"pipx:graph-cli" = "latest"
"pipx:trafilatura" = "latest"

"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:bat" = "latest"
"cargo:sheldon" = "latest"
"cargo:git-delta" = "latest"
"cargo:zoxide" = "latest"

"github:ktr0731/evans" = "latest"
"github:k1LoW/octocov" = "latest"

claude = { version = "latest", bin = "claude", platforms = """
[linux-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/linux-arm64/claude"

[linux-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/linux-x64/claude"

[macos-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/darwin-arm64/claude"

[macos-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/darwin-x64/claude"
""", version_list_url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/latest" }
"github:caarlos0/mdtree" = "latest"
direnv = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"cargo:pik" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby","node","java"]
